#ifndef	__CURSPOS_H__
#define __CURSPOS_H__

#define WINDOW_ORIGIN_COL 1
#define WINDOW_ORIGIN_ROW 1

#define WINDOW_BORDER 1

#define MESSAGE_WINDOW_COL 60
#define MESSAGE_WINDOW_ROW 20 

#define SEND_WINDOW_COL 60
#define SEND_WINDOW_ROW 6 

#define FRILIST_WINDOW_COL 16
#define FRILIST_WINDOW_ROW 27 

#define	MESSAGE_WINDOW_OFFSET_COL (WINDOW_ORIGIN_COL + 1*WINDOW_BORDER)
#define MESSAGE_WINDOW_OFFSET_ROW (WINDOW_ORIGIN_ROW + 3*WINDOW_BORDER)

#define SEND_WINDOW_OFFSET_COL (WINDOW_ORIGIN_COL + 1*WINDOW_BORDER)
#define SEND_WINDOW_OFFSET_ROW (MESSAGE_WINDOW_OFFSET_ROW + MESSAGE_WINDOW_ROW + WINDOW_BORDER)

#define FRILIST_WINDOW_OFFSET_COL (MESSAGE_WINDOW_OFFSET_COL + MESSAGE_WINDOW_COL +WINDOW_BORDER)
#define FRILIST_WINDOW_OFFSET_ROW (WINDOW_ORIGIN_ROW + 3*WINDOW_BORDER)

// windows borders
#define MESSAGE_TOP_BORDER	MESSAGE_WINDOW_OFFSET_ROW
#define MESSAGE_BOTTOM_BORDER	(MESSAGE_WINDOW_OFFSET_ROW + MESSAGE_WINDOW_ROW - 1)
#define MESSAGE_LEFT_BORDER	MESSAGE_WINDOW_OFFSET_COL
#define MESSAGE_RIGHT_BORDER	(MESSAGE_WINDOW_OFFSET_COL + MESSAGE_WINDOW_COL - 1)

#define SEND_TOP_BORDER	        SEND_WINDOW_OFFSET_ROW
#define SEND_BOTTOM_BORDER	(SEND_WINDOW_OFFSET_ROW + SEND_WINDOW_ROW - 1)
#define SEND_LEFT_BORDER	SEND_WINDOW_OFFSET_COL
#define SEND_RIGHT_BORDER	(SEND_WINDOW_OFFSET_COL + SEND_WINDOW_COL - 1)

#define FRILIST_TOP_BORDER	FRILIST_WINDOW_OFFSET_ROW
#define FRILIST_BOTTOM_BORDER	(FRILIST_WINDOW_OFFSET_ROW + FRILIST_WINDOW_ROW - 1)
#define FRILIST_LEFT_BORDER	FRILIST_WINDOW_OFFSET_COL
#define FRILIST_RIGHT_BORDER	(FRILIST_WINDOW_OFFSET_COL + FRILIST_WINDOW_COL - 1)

#endif
